version: "3.8"

services:
  db:
    image: postgres:14.2
    container_name: sample_app_db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=sample_app_dev
    ports:
      - "5432:5432"
  redis:
    image: redis:6.2.10
    container_name: sample_app_redis
    ports:
      - "6379:6379"
